---
- name: install_vms
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  roles:
    - install_vms

- name: Postgres
  hosts: all
  become: yes
  tasks:
  #install vim,  telnet 
  - name: install base tools
    dnf:
      name:
        - vim
        - telnet
      state: present
      update_cache: true

  # install_postgres,  postgres_replication on node-maste,  node-slave
- name: install postgres 16 and set up replication
  hosts: node1,node2
  become: yes
  roles:
   - install_postgres
   - postgres_replication
   
# install_barman
- name: set up backup
  hosts: all
  become: yes
  roles:
   - install_barman
